name: Tmate VPS

on:
  workflow_dispatch:

jobs:
  vps:
    runs-on: ubuntu-latest
    timeout-minutes: 355

    steps:
      - name: Start tmate
        uses: mxschmitt/action-tmate@v3
        timeout-minutes: 350
        with:
          detached: false
          connect-timeout-seconds: 60
